### ISSUE TITLE
录音后无法保存成功，看不到录音列表

### ISSUE THREAD

**Issue by super-qc** [jaydenxiao2016/VoiceManager#5]
12-04 11:09:17.974 25305-25305/com.jaydenxiao.voicemanager V/AudioManager: playSoundEffect   effectType: 0
12-04 11:09:17.974 25305-25305/com.jaydenxiao.voicemanager V/AudioManager: querySoundEffectsEnabled...
12-04 11:09:17.974 25305-25305/com.jaydenxiao.voicemanager I/MediaRecorder: stop
12-04 11:09:17.974 25305-25305/com.jaydenxiao.voicemanager E/MediaRecorder: stop called in an invalid state: 0
12-04 11:09:17.976 25305-25305/com.jaydenxiao.voicemanager W/System.err: java.io.FileNotFoundException: /storage/emulated/0/VoiceManager/audio/20171204-110913.amr (No such file or directory)
12-04 11:09:17.976 25305-25305/com.jaydenxiao.voicemanager W/System.err:     at java.io.FileInputStream.open(Native Method)
12-04 11:09:17.976 25305-25305/com.jaydenxiao.voicemanager W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:146)
12-04 11:09:17.976 25305-25305/com.jaydenxiao.voicemanager W/System.err:     at com.jaydenxiao.voicemanager.VoiceManager.getOutputVoiceFile(VoiceManager.java:319)
12-04 11:09:17.976 25305-25305/com.jaydenxiao.voicemanager W/System.err:     at com.jaydenxiao.voicemanager.VoiceManager.stopVoiceRecord(VoiceManager.java:200)
12-04 11:09:17.976 25305-25305/com.jaydenxiao.voicemanager W/System.err:     at com.jaydenxiao.voicemanager.RecordVoiceButton$2.onClick(RecordVoiceButton.java:86)
12-04 11:09:17.976 25305-25305/com.jaydenxiao.voicemanager W/System.err:     at android.view.View.performClick(View.java:5646)
12-04 11:09:17.976 25305-25305/com.jaydenxiao.voicemanager W/System.err:     at android.view.View$PerformClick.run(View.java:22459)
12-04 11:09:17.976 25305-25305/com.jaydenxiao.voicemanager W/System.err:     at android.os.Handler.handleCallback(Handler.java:761)
12-04 11:09:17.976 25305-25305/com.jaydenxiao.voicemanager W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
12-04 11:09:17.976 25305-25305/com.jaydenxiao.voicemanager W/System.err:     at android.os.Looper.loop(Looper.java:156)
12-04 11:09:17.976 25305-25305/com.jaydenxiao.voicemanager W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6523)
12-04 11:09:17.976 25305-25305/com.jaydenxiao.voicemanager W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
12-04 11:09:17.976 25305-25305/com.jaydenxiao.voicemanager W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
12-04 11:09:17.976 25305-25305/com.jaydenxiao.voicemanager W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
12-04 11:09:17.978 25305-25305/com.jaydenxiao.voicemanager W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.FileOutputStream.close()' on a null object reference
12-04 11:09:17.978 25305-25305/com.jaydenxiao.voicemanager W/System.err:     at com.jaydenxiao.voicemanager.VoiceManager.getOutputVoiceFile(VoiceManager.java:343)
12-04 11:09:17.978 25305-25305/com.jaydenxiao.voicemanager W/System.err:     at com.jaydenxiao.voicemanager.VoiceManager.stopVoiceRecord(VoiceManager.java:200)
12-04 11:09:17.978 25305-25305/com.jaydenxiao.voicemanager W/System.err:     at com.jaydenxiao.voicemanager.RecordVoiceButton$2.onClick(RecordVoiceButton.java:86)
12-04 11:09:17.978 25305-25305/com.jaydenxiao.voicemanager W/System.err:     at android.view.View.performClick(View.java:5646)
12-04 11:09:17.978 25305-25305/com.jaydenxiao.voicemanager W/System.err:     at android.view.View$PerformClick.run(View.java:22459)
12-04 11:09:17.978 25305-25305/com.jaydenxiao.voicemanager W/System.err:     at android.os.Handler.handleCallback(Handler.java:761)
12-04 11:09:17.978 25305-25305/com.jaydenxiao.voicemanager W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
12-04 11:09:17.978 25305-25305/com.jaydenxiao.voicemanager W/System.err:     at android.os.Looper.loop(Looper.java:156)
12-04 11:09:17.978 25305-25305/com.jaydenxiao.voicemanager W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6523)
12-04 11:09:17.978 25305-25305/com.jaydenxiao.voicemanager W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
12-04 11:09:17.978 25305-25305/com.jaydenxiao.voicemanager W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
12-04 11:09:17.978 25305-25305/com.jaydenxiao.voicemanager W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by neo1201** [comment]
应该事6.0以上的系统，没有添加权限

**Comment by super-qc** [comment]
好的，谢谢
